// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.12.4
// source: user/role.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';
import { UserRoles } from './user-enums';
import { CRYPO_AUTH_PACKAGE_NAME } from '../auth/auth';

export const protobufPackage = 'crypo.role';

export interface RoleList {
  roles: Role[];
}

export interface Role {
  id: number;
  name: string;
  role: UserRoles;
  icon: string;
  color: string;
  grants: Grant[];
}

export interface GetRoleRequest {
  id: number;
}

export interface DeleteRoleRequest {
  id: number;
}

export interface DeleteRoleResponse {
  success: boolean;
}

export interface GrantList {
  grants: Grant[];
}

export interface Grant {
  role: UserRoles;
  resource: string;
  action: string;
  attributes: string[];
}

export interface SetGrantsRequest {
  roleId: number;
  grants: SetGrantByRole[];
}

export interface SetGrantByRole {
  resource: string;
  action: string;
  attributes: string[];
}

export interface Stub {}

export const CRYPO_ROLE_PACKAGE_NAME = 'crypo.role';

export interface RoleServiceClient {
  /** Roles */

  createRole(request: Role): Observable<Role>;

  getRoles(request: Stub): Observable<RoleList>;

  getRole(request: GetRoleRequest): Observable<Role>;

  getRolesWithGrant(request: Stub): Observable<RoleList>;

  updateRole(request: Role): Observable<Role>;

  deleteRole(request: DeleteRoleRequest): Observable<DeleteRoleResponse>;

  /** Grants */

  setGrants(request: SetGrantsRequest): Observable<Role>;

  getGrants(request: Stub): Observable<GrantList>;

  getGrantByRole(request: GetRoleRequest): Observable<GrantList>;
}

export interface RoleServiceController {
  /** Roles */

  createRole(request: Role): Promise<Role> | Observable<Role> | Role;

  getRoles(request: Stub): Promise<RoleList> | Observable<RoleList> | RoleList;

  getRole(request: GetRoleRequest): Promise<Role> | Observable<Role> | Role;

  getRolesWithGrant(
    request: Stub,
  ): Promise<RoleList> | Observable<RoleList> | RoleList;

  updateRole(request: Role): Promise<Role> | Observable<Role> | Role;

  deleteRole(
    request: DeleteRoleRequest,
  ):
    | Promise<DeleteRoleResponse>
    | Observable<DeleteRoleResponse>
    | DeleteRoleResponse;

  /** Grants */

  setGrants(request: SetGrantsRequest): Promise<Role> | Observable<Role> | Role;

  getGrants(
    request: Stub,
  ): Promise<GrantList> | Observable<GrantList> | GrantList;

  getGrantByRole(
    request: GetRoleRequest,
  ): Promise<GrantList> | Observable<GrantList> | GrantList;
}

export function RoleServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      'createRole',
      'getRoles',
      'getRole',
      'getRolesWithGrant',
      'updateRole',
      'deleteRole',
      'setGrants',
      'getGrants',
      'getGrantByRole',
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcMethod('RoleService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(
        constructor.prototype,
        method,
      );
      GrpcStreamMethod('RoleService', method)(
        constructor.prototype[method],
        method,
        descriptor,
      );
    }
  };
}

export const ROLE_SERVICE_NAME = 'RoleService';
