// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.12.4
// source: user/user-enums.proto

/* eslint-disable */

import { CRYPO_AUTH_PACKAGE_NAME } from '../auth/auth';

export const protobufPackage = 'crypo.user';

export enum UserRoles {
  USER_ROLES_UNSPECIFIED = 0,
  USER_ROLES_SUPER_ADMIN = 1,
  USER_ROLES_ADMIN = 2,
  USER_ROLES_USER = 3,
  UNRECOGNIZED = -1,
}

export enum AvailableUserFilterProps {
  EMAIL = 0,
  PHONE = 1,
  ID = 2,
  UNRECOGNIZED = -1,
}

export const CRYPO_USER_PACKAGE_NAME = 'crypo.user';
